### ISSUE TITLE
color checker enabled in dock task worlds

### ISSUE THREAD

**Issue by osrf-migration** [osrf/vrx#186]
**Original report ([archived issue](https://osrf-migration.github.io/vrx-gh-pages/#!/osrf/vrx/issues/186)) by Michael McCarrin (Bitbucket: [m1chaelm](https://bitbucket.org/%7B3c3f500d-bbf6-472c-b8f7-627e5eabc226%7D/)).**

----------------------------------------
As mentioned in [this forum thread](https://robonationforum.vbulletin.net/node/2718), it appears that we left the color checker on in our dock tasks, which allowed Georgia tech to score 10 points in the dress rehearsal by sending the default color sequence even though no light buoy was displayed. The fix is to make sure we set enable\_color\_checker to false in our dock \(“scan”\) task worlds. We may also want to fix it in the worlds we’ve already released and in the yaml that generates them.

**Comment by M1chaelM** [comment]
Verified this has been fixed in the following worlds:
* [x] vrx_gazebo/worlds/2019_practice/dock*.world
* [x] vrx_gazebo/worlds/2019_phase2/dock*.world
* [x] vrx_gazebo/worlds/xacros/dock.xacro
* [x] vrx_2019/worlds/dock.world.xacro
* [x] All private competition world yaml for 2019.
* [x] task_config/dock.yaml in the vrx-docker repository

I think the above list is exhaustive so I am closing this issue.
