### ISSUE TITLE
Create a tutorial for running the competition and evaluating a submission

### ISSUE THREAD

**Issue by caguero** [osrf/vrx#287]
Running the competition evaluating all the submissions is a task that we do to run the competition. Before that, it's important to document the process and show the teams how to run it by themselves. They'll be able to catch potential issues with their submissions and get real scores.

**Comment by M1chaelM** [comment]
* A new tutorial is now available here: https://github.com/osrf/vrx/wiki/vrx_2022-testing
* It can be tested simultaneously with https://github.com/osrf/vrx-docker/pull/34

Notes:
* Our world-generation scripts are currently broken due to issue #348, so I've reworked the tutorial to use pre-built worlds.
* We have not yet made the VRX 2022 worlds available (these were planned for 9/24) so the tutorial uses the VRX 2019 practice worlds.

**Comment by M1chaelM** [comment]
I'm not closing this yet because we should update the tutorial to use 2022 practice worlds when #331 is merged.

**Comment by M1chaelM** [comment]
Now updated to use 2022 practice worlds.
