### ISSUE TITLE
Not an issue, just a question

### ISSUE THREAD

**Issue by davihdsantos** [osrf/vrx#297]
Hello,

What exactly is the advantage of following the tutorial **https://github.com/osrf/vrx/wiki/tutorials -> System Setup -> Use a Docker Image** if every user has to build their own image from zero?

Is it possible to build a working image and push to https://hub.docker.com/r/osrf/vrx/tags?page=1&ordering=last_updated ?

Thanks!

**Comment by bsb808** [comment]
Hi,
The advantages include such things as being able to run the development environment without needing to reinstall your OS and having a 'clean' development environment in terms of dependencies for developing and deploying code.  The dockerfile is also used as a basis for CI within the project.

While we would like to be able to have an downloadable image that is always at the latest, managing and maintaining a known-good docker image on dockerhub is just something we don't have the resources to support.  It may seem like a small thing, but in our experience maintaining an image that is properly tested and deployed adds an element of support that takes away from being able to develop new features.

Also, since the competition requires folks to deploy their code via docker, the barrier to entry of building an image from the Dockerfile should be small.  Building the image does take some time, but the 10-15 minutes is well worth it.

Brian
